services:
  wp:
    container_name: wp
    image: wp
    restart: always
    depends_on:
      - mysql
    ports:
      - "8000:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}  
    volumes:
      - ./wp:/var/www/html
      - ./theme-demo:/var/www/html/wp-content/themes/theme-demo
    networks:
      main:
        aliases:
          - wp
  mysql:
    container_name: mysql
    image: mysql:5.7
    volumes:
      - db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      main:
        aliases:
          - mysql

volumes:
  wp-data: {}
  db: {}
networks:
  main: