version: '3.7'
volumes:
  wp-data:
networks:
  wp-back:
services:
  wp:
    container_name: wp
    image: wp
    restart: always
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    # command: >
    #   #!/bin/bash
    #   bash /home/activateSendmail.sh
    #   /etc/init.d/sendmail start    
    volumes:
      - ./wp:/var/www/html
    networks:
      main:
        aliases:
          - wp
  mysql:
    container_name: mysql
    image: mysql
    volumes:
      - /mnt/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      main:
        aliases:
          - mysql

networks:
  main:

volumes:
  {}

